version: "3.9"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#  web:
#    build: .
#    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    environment:
#      POSTGRES_SERVER: localhost
#      POSTGRES_PORT: ${POSTGRES_PORT}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    depends_on:
#      - postgres
#  tests:
#    build: .
#    command: pytest
#
#    volumes:
#      - .:/code
#    environment:
#      POSTGRES_SERVER: postgres
#      POSTGRES_PORT: ${POSTGRES_PORT}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    depends_on:
#      - postgres
volumes:
  postgres_data: